services:
  bitcoind:
    container_name: bitcoind-node
    hostname: bitcoind-node
    image: kylemanna/bitcoind@sha256:2400e64960457b22be55299a2d7fa2aaa217f3dfc4afb84387e5511fe8ce5055
    # restart: unless-stopped
    volumes:
      - ./bitcoind-data:/bitcoin/.bitcoin
    environment:
      - REGTEST=1 
      - DISABLEWALLET=0 
      - PRINTTOCONSOLE=1
      - RPCUSER=user
      - RPCPASSWORD=password

    ports:
      - 18444:8333
      - 127.0.0.1:18443:8332
    post_start:
      - command: "sleep 0.5"
      - command: "bitcoin-cli -regtest -rpcport=8332 loadwallet nativewallet"

  btcd:
    profiles:
      - donotstart
    container_name: btcd
    hostname: btcd
    build: https://github.com/btcsuite/btcd.git#master
    volumes:
      - btcd-data:/root/.btcd
    ports:
      - 18333:18333
      - 18334:18334
    # https://github.com/btcsuite/btcd/blob/master/docs/configuration.md
    command:
      [
        "--simnet",
        "--rpcuser=[CHOOSE_A_USERNAME]",
        "--rpcpass=[CREATE_A_VERY_HARD_PASSWORD]",
      ]

volumes:
  btcd-data:
