with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
inpackage: True
packages:
  github.com/gonative-cc/relayer/bitcoinspv/clients:
    config:
      dir: "bitcoinspv/clients/mocks"
      outpkg: "clients/mocks"
    interfaces:
      BTCClient:
      BitcoinSPV:
