# Relayer Configuration

native:
  native_rpc: "127.0.0.1:26657"
  native_grpc: "127.0.0.1:9090"       

ika:
  rpc: "127.0.0.1:0001"
  signer_mnemonic: "require fish happy collect verify bind media unknown media picnic tuna virus"
  native_lc_package: "0xbc39bc608dd3481a6c7f15dd25021225db7f70579d50e45aacb631612fbe3d59"
  native_lc_module: "0xbc39bc608dd3481a6c7f15dd25021225db7f70579d50e45aacb631612fbe3d59"
  native_lc_function: "0xbc39bc608dd3481a6c7f15dd25021225db7f70579d50e45aacb631612fbe3d59"
  gas_acc: "0xbc39bc608dd3481a6c7f15dd25021225db7f70579d50e45aacb631612fbe3d59"                            
  gas_budget: 100000

bitcoin:
  rpc_host: "your-bitcoin-rpc.com"
  rpc_user: "your-bitcoin-rpc-user"
  rpc_pass: "your-bitcoin-rpc-password"
  confirmation_threshold: 6
  http_post_mode: true
  disable_tls: false
  network: "regtest"

relayer:
  process_txs_interval: 5s
  confirm_txs_interval: 7s
  sign_req_fetch_interval: 5s
  sign_req_fetch_from: 0
  sign_req_fetch_limit: 5

db:
  file: "relayer.db"
