package native

//go:generate msgp

// SignReq represents a signature request.
type SignReq struct {
	ID        uint64 // Unique sequence number for the sign request
	Payload   []byte // Bytes to be signed
	DWalletID string // ID of the  dwallet
	UserSig   string // Partial signature created with the user's share of the private key
	FinalSig  []byte // Full signature generated by the IKA network
	Timestamp int64  // Timestamp of the sign request (in Unix time)
}

// SignReqs is a slice of SignReq
type SignReqs []SignReq
