name: Sui E2E Tests

on:
  pull_request:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Sui Local Network (Manual Docker Run)

        run: |
          docker run -d --name sui-node -p 9000:9000 -p 9123:9123 mysten/sui-tools:devnet /bin/bash -c "RUST_LOG='off,sui_node=info' sui start --with-faucet --force-regenesis"
          CONTAINER_ID=$(docker ps -aqf "name=sui-node")
          echo "container_id=$CONTAINER_ID" >> $GITHUB_OUTPUT

      - name: Wait for Local Sui Network
        run: sleep 10

      - name: Configure Sui Client
        run: |
          docker exec sui-node sui client -y
          docker exec sui-node sui client new-env --alias local --rpc http://127.0.0.1:9000
          docker exec sui-node sui client switch --env local

      - name: Ping Sui Network
        run: |
          RESPONSE=$(curl --location --request POST 'http://127.0.0.1:9000' \
             --header 'Content-Type: application/json' \
             --data-raw '{
               "jsonrpc": "2.0",
               "id": 1,
               "method": "sui_getTotalTransactionBlocks",
               "params": []
             }')

           echo "Sui Network Response: $RESPONSE"

      - name: Show active address
        run: docker exec sui-node sui client active-address

      - name: Get SUI from faucet
        run: docker exec sui-node sui client faucet

      - name: Get SUI balance of active address
        run: docker exec sui-node sui client gas

      - name: Deploy and initalize Light Client
        run: echo "deploy and initalize light client"

      - name: Run e2e
        run: echo "run e2e"



        curl --location --request POST 'http://127.0.0.1:9000' --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0","id": 1,"method": "sui_getTotalTransactionBlocks","params": []}'