name: E2E Tests

on:
  pull_request:
    branches:
      - master

jobs:
  check-repo-status:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
          FILES: |
            go.mod
            go.sum
      - id: check
        run: |
          echo "status=${env.GIT_DIFF}"
          echo "status=${env.GIT_DIFF}" >> "$GITHUB_OUTPUT"

  e2e-tests:
    runs-on: ubuntu-latest
    needs: check-repo-status
    if: ${{ needs.check-repo-status.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzmq3-dev pkg-config
      - name: Compile
        run: |
          go mod download
          make build

      - name: Start Services
        run: ./e2e/start_services.sh

      - name: Wait for the services to start
        run: sleep 20

      - name: Ping Sui Network
        run: |
          RESPONSE=$(curl --location --request POST 'http://127.0.0.1:9000' \
             --header 'Content-Type: application/json' \
             --data-raw '{
               "jsonrpc": "2.0",
               "id": 1,
               "method": "sui_getTotalTransactionBlocks",
               "params": []
             }')

           echo "Sui Network Response: $RESPONSE"

      - name: Initialize Local Network
        run: ./e2e/init_local_net.sh

      - name: Publish and Initalize Light Client
        run: ./e2e/deploy_light_client_alpha.sh

      - name: Run E2E Tests
        run: ./e2e/run_e2e_tests.sh
        # run: echo "E2E can't run on CI/CD yet"

      - name: Stop Services (Docker Compose)
        if: always()
        run: docker compose -f contrib/docker-compose.yaml down -v
