name: Sui E2E Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Start Services
        run: ./e2e/start_services.sh

      - name: Initialize Local Network and Deploy Light Client
        run: ./e2e/init_local_net.sh

      - name: Run E2E Tests
        run: ./e2e/run_e2e_tests.sh

      - name: Stop Services (Docker Compose)
        if: always()
        run: docker compose -f contrib/docker-compose.yaml down -v
